#ifndef KAFKAAPI_H
#define KAFKAAPI_H

#define API_SET_KAFKATAG 72
#define API_SET_KAFKA_START_ID 74
#define API_SET_KAFKATOPIC 79
#define API_GET_KAFKATAG 82
#define API_GET_KAFKATOPIC 89
#define API_GET_KAFKA_START_ID 90

#endif // API_H
