# Makefile.in generated by automake 1.16.2 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2020 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/almond
pkgincludedir = $(includedir)/almond
pkglibdir = $(libdir)/almond
pkglibexecdir = $(libexecdir)/almond
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = almond$(EXEEXT)
#am__append_1 = main_s.c api_s.c $(COMMON_SOURCES)
am__append_2 = main.c api.c $(COMMON_SOURCES) mod_kafka.c
am__append_3 = -I/usr/include/librdkafka
am__append_4 = -lrdkafka
#am__append_5 = main.c api.c  $(COMMON_SOURCES) mod_avro.c
#am__append_6 = -I/usr/include/librdkafka -I/usr/include/avro -I/usr/include/libserdes
#am__append_7 = -lrdkafka -lserdes -lavro
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__almond_SOURCES_DIST = main_s.c api_s.c plugins.c logger.c config.c \
	collect.c jwt_validate.c main.c api.c mod_kafka.c mod_avro.c
am__objects_1 = almond-plugins.$(OBJEXT) almond-logger.$(OBJEXT) \
	almond-config.$(OBJEXT) almond-collect.$(OBJEXT) \
	almond-jwt_validate.$(OBJEXT)
#am__objects_2 = almond-main_s.$(OBJEXT) \
#	almond-api_s.$(OBJEXT) $(am__objects_1)
am__objects_3 = almond-main.$(OBJEXT) \
	almond-api.$(OBJEXT) $(am__objects_1) \
	almond-mod_kafka.$(OBJEXT)
#am__objects_4 = almond-main.$(OBJEXT) \
#	almond-api.$(OBJEXT) $(am__objects_1) \
#	almond-mod_avro.$(OBJEXT)
am_almond_OBJECTS = $(am__objects_2) $(am__objects_3) $(am__objects_4)
almond_OBJECTS = $(am_almond_OBJECTS)
am__DEPENDENCIES_1 =
almond_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
almond_LINK = $(CCLD) $(almond_CFLAGS) $(CFLAGS) $(almond_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/almond-api.Po \
	./$(DEPDIR)/almond-api_s.Po ./$(DEPDIR)/almond-collect.Po \
	./$(DEPDIR)/almond-config.Po \
	./$(DEPDIR)/almond-jwt_validate.Po \
	./$(DEPDIR)/almond-logger.Po ./$(DEPDIR)/almond-main.Po \
	./$(DEPDIR)/almond-main_s.Po ./$(DEPDIR)/almond-mod_avro.Po \
	./$(DEPDIR)/almond-mod_kafka.Po ./$(DEPDIR)/almond-plugins.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(almond_SOURCES)
DIST_SOURCES = $(am__almond_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP) \
	config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in README \
	compile config.guess config.sub depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /workspace/almond-0.9.30/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /workspace/almond-0.9.30/missing autoconf
AUTOHEADER = ${SHELL} /workspace/almond-0.9.30/missing autoheader
AUTOMAKE = ${SHELL} /workspace/almond-0.9.30/missing automake-1.16
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS =  -I/usr/include -I/usr/local/include
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JWT_LIBS = -ljwt
LDFLAGS =  -L/usr/lib64 -L/usr/local/lib -L/usr/lib
LIBOBJS = 
LIBS = -lrdkafka 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /workspace/almond-0.9.30/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = almond
PACKAGE_BUGREPORT = andreas.lindell@almondmonitor.com
PACKAGE_NAME = almond
PACKAGE_STRING = almond 0.9.30
PACKAGE_TARNAME = almond
PACKAGE_URL = 
PACKAGE_VERSION = 0.9.30
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.9.30
abs_builddir = /workspace/almond-0.9.30
abs_srcdir = /workspace/almond-0.9.30
abs_top_builddir = /workspace/almond-0.9.30
abs_top_srcdir = /workspace/almond-0.9.30
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /workspace/almond-0.9.30/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /opt/almond
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
almond_SOURCES = $(am__append_1) $(am__append_2) $(am__append_5)
COMMON_SOURCES = plugins.c logger.c config.c collect.c jwt_validate.c
AM_CPPFLAGS = -I/usr/include
AM_LDFLAGS = -L/usr/lib64 -L/usr/local/lib -L/usr/lib

# Default flags
almond_CPPFLAGS = -I/usr/include/json_c $(am__append_3) \
	$(am__append_6)
almond_CFLAGS = -g -Wall -std=c99 -O0
almond_LDFLAGS = -L/usr/lib/x86_64-linux-gnu -fstack-protector
almond_LDADD = -lpthread -ljson-c -lcurl -lssl -lcrypto -lz \
	$(JWT_LIBS) $(am__append_4) $(am__append_7)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

almond$(EXEEXT): $(almond_OBJECTS) $(almond_DEPENDENCIES) $(EXTRA_almond_DEPENDENCIES) 
	@rm -f almond$(EXEEXT)
	$(AM_V_CCLD)$(almond_LINK) $(almond_OBJECTS) $(almond_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/almond-api.Po # am--include-marker
include ./$(DEPDIR)/almond-api_s.Po # am--include-marker
include ./$(DEPDIR)/almond-collect.Po # am--include-marker
include ./$(DEPDIR)/almond-config.Po # am--include-marker
include ./$(DEPDIR)/almond-jwt_validate.Po # am--include-marker
include ./$(DEPDIR)/almond-logger.Po # am--include-marker
include ./$(DEPDIR)/almond-main.Po # am--include-marker
include ./$(DEPDIR)/almond-main_s.Po # am--include-marker
include ./$(DEPDIR)/almond-mod_avro.Po # am--include-marker
include ./$(DEPDIR)/almond-mod_kafka.Po # am--include-marker
include ./$(DEPDIR)/almond-plugins.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

almond-main_s.o: main_s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-main_s.o -MD -MP -MF $(DEPDIR)/almond-main_s.Tpo -c -o almond-main_s.o `test -f 'main_s.c' || echo '$(srcdir)/'`main_s.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-main_s.Tpo $(DEPDIR)/almond-main_s.Po
#	$(AM_V_CC)source='main_s.c' object='almond-main_s.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-main_s.o `test -f 'main_s.c' || echo '$(srcdir)/'`main_s.c

almond-main_s.obj: main_s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-main_s.obj -MD -MP -MF $(DEPDIR)/almond-main_s.Tpo -c -o almond-main_s.obj `if test -f 'main_s.c'; then $(CYGPATH_W) 'main_s.c'; else $(CYGPATH_W) '$(srcdir)/main_s.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-main_s.Tpo $(DEPDIR)/almond-main_s.Po
#	$(AM_V_CC)source='main_s.c' object='almond-main_s.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-main_s.obj `if test -f 'main_s.c'; then $(CYGPATH_W) 'main_s.c'; else $(CYGPATH_W) '$(srcdir)/main_s.c'; fi`

almond-api_s.o: api_s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-api_s.o -MD -MP -MF $(DEPDIR)/almond-api_s.Tpo -c -o almond-api_s.o `test -f 'api_s.c' || echo '$(srcdir)/'`api_s.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-api_s.Tpo $(DEPDIR)/almond-api_s.Po
#	$(AM_V_CC)source='api_s.c' object='almond-api_s.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-api_s.o `test -f 'api_s.c' || echo '$(srcdir)/'`api_s.c

almond-api_s.obj: api_s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-api_s.obj -MD -MP -MF $(DEPDIR)/almond-api_s.Tpo -c -o almond-api_s.obj `if test -f 'api_s.c'; then $(CYGPATH_W) 'api_s.c'; else $(CYGPATH_W) '$(srcdir)/api_s.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-api_s.Tpo $(DEPDIR)/almond-api_s.Po
#	$(AM_V_CC)source='api_s.c' object='almond-api_s.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-api_s.obj `if test -f 'api_s.c'; then $(CYGPATH_W) 'api_s.c'; else $(CYGPATH_W) '$(srcdir)/api_s.c'; fi`

almond-plugins.o: plugins.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-plugins.o -MD -MP -MF $(DEPDIR)/almond-plugins.Tpo -c -o almond-plugins.o `test -f 'plugins.c' || echo '$(srcdir)/'`plugins.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-plugins.Tpo $(DEPDIR)/almond-plugins.Po
#	$(AM_V_CC)source='plugins.c' object='almond-plugins.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-plugins.o `test -f 'plugins.c' || echo '$(srcdir)/'`plugins.c

almond-plugins.obj: plugins.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-plugins.obj -MD -MP -MF $(DEPDIR)/almond-plugins.Tpo -c -o almond-plugins.obj `if test -f 'plugins.c'; then $(CYGPATH_W) 'plugins.c'; else $(CYGPATH_W) '$(srcdir)/plugins.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-plugins.Tpo $(DEPDIR)/almond-plugins.Po
#	$(AM_V_CC)source='plugins.c' object='almond-plugins.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-plugins.obj `if test -f 'plugins.c'; then $(CYGPATH_W) 'plugins.c'; else $(CYGPATH_W) '$(srcdir)/plugins.c'; fi`

almond-logger.o: logger.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-logger.o -MD -MP -MF $(DEPDIR)/almond-logger.Tpo -c -o almond-logger.o `test -f 'logger.c' || echo '$(srcdir)/'`logger.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-logger.Tpo $(DEPDIR)/almond-logger.Po
#	$(AM_V_CC)source='logger.c' object='almond-logger.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-logger.o `test -f 'logger.c' || echo '$(srcdir)/'`logger.c

almond-logger.obj: logger.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-logger.obj -MD -MP -MF $(DEPDIR)/almond-logger.Tpo -c -o almond-logger.obj `if test -f 'logger.c'; then $(CYGPATH_W) 'logger.c'; else $(CYGPATH_W) '$(srcdir)/logger.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-logger.Tpo $(DEPDIR)/almond-logger.Po
#	$(AM_V_CC)source='logger.c' object='almond-logger.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-logger.obj `if test -f 'logger.c'; then $(CYGPATH_W) 'logger.c'; else $(CYGPATH_W) '$(srcdir)/logger.c'; fi`

almond-config.o: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-config.o -MD -MP -MF $(DEPDIR)/almond-config.Tpo -c -o almond-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-config.Tpo $(DEPDIR)/almond-config.Po
#	$(AM_V_CC)source='config.c' object='almond-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c

almond-config.obj: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-config.obj -MD -MP -MF $(DEPDIR)/almond-config.Tpo -c -o almond-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-config.Tpo $(DEPDIR)/almond-config.Po
#	$(AM_V_CC)source='config.c' object='almond-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`

almond-collect.o: collect.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-collect.o -MD -MP -MF $(DEPDIR)/almond-collect.Tpo -c -o almond-collect.o `test -f 'collect.c' || echo '$(srcdir)/'`collect.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-collect.Tpo $(DEPDIR)/almond-collect.Po
#	$(AM_V_CC)source='collect.c' object='almond-collect.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-collect.o `test -f 'collect.c' || echo '$(srcdir)/'`collect.c

almond-collect.obj: collect.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-collect.obj -MD -MP -MF $(DEPDIR)/almond-collect.Tpo -c -o almond-collect.obj `if test -f 'collect.c'; then $(CYGPATH_W) 'collect.c'; else $(CYGPATH_W) '$(srcdir)/collect.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-collect.Tpo $(DEPDIR)/almond-collect.Po
#	$(AM_V_CC)source='collect.c' object='almond-collect.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-collect.obj `if test -f 'collect.c'; then $(CYGPATH_W) 'collect.c'; else $(CYGPATH_W) '$(srcdir)/collect.c'; fi`

almond-jwt_validate.o: jwt_validate.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-jwt_validate.o -MD -MP -MF $(DEPDIR)/almond-jwt_validate.Tpo -c -o almond-jwt_validate.o `test -f 'jwt_validate.c' || echo '$(srcdir)/'`jwt_validate.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-jwt_validate.Tpo $(DEPDIR)/almond-jwt_validate.Po
#	$(AM_V_CC)source='jwt_validate.c' object='almond-jwt_validate.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-jwt_validate.o `test -f 'jwt_validate.c' || echo '$(srcdir)/'`jwt_validate.c

almond-jwt_validate.obj: jwt_validate.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-jwt_validate.obj -MD -MP -MF $(DEPDIR)/almond-jwt_validate.Tpo -c -o almond-jwt_validate.obj `if test -f 'jwt_validate.c'; then $(CYGPATH_W) 'jwt_validate.c'; else $(CYGPATH_W) '$(srcdir)/jwt_validate.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-jwt_validate.Tpo $(DEPDIR)/almond-jwt_validate.Po
#	$(AM_V_CC)source='jwt_validate.c' object='almond-jwt_validate.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-jwt_validate.obj `if test -f 'jwt_validate.c'; then $(CYGPATH_W) 'jwt_validate.c'; else $(CYGPATH_W) '$(srcdir)/jwt_validate.c'; fi`

almond-main.o: main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-main.o -MD -MP -MF $(DEPDIR)/almond-main.Tpo -c -o almond-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-main.Tpo $(DEPDIR)/almond-main.Po
#	$(AM_V_CC)source='main.c' object='almond-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-main.o `test -f 'main.c' || echo '$(srcdir)/'`main.c

almond-main.obj: main.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-main.obj -MD -MP -MF $(DEPDIR)/almond-main.Tpo -c -o almond-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-main.Tpo $(DEPDIR)/almond-main.Po
#	$(AM_V_CC)source='main.c' object='almond-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-main.obj `if test -f 'main.c'; then $(CYGPATH_W) 'main.c'; else $(CYGPATH_W) '$(srcdir)/main.c'; fi`

almond-api.o: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-api.o -MD -MP -MF $(DEPDIR)/almond-api.Tpo -c -o almond-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-api.Tpo $(DEPDIR)/almond-api.Po
#	$(AM_V_CC)source='api.c' object='almond-api.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-api.o `test -f 'api.c' || echo '$(srcdir)/'`api.c

almond-api.obj: api.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-api.obj -MD -MP -MF $(DEPDIR)/almond-api.Tpo -c -o almond-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-api.Tpo $(DEPDIR)/almond-api.Po
#	$(AM_V_CC)source='api.c' object='almond-api.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-api.obj `if test -f 'api.c'; then $(CYGPATH_W) 'api.c'; else $(CYGPATH_W) '$(srcdir)/api.c'; fi`

almond-mod_kafka.o: mod_kafka.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-mod_kafka.o -MD -MP -MF $(DEPDIR)/almond-mod_kafka.Tpo -c -o almond-mod_kafka.o `test -f 'mod_kafka.c' || echo '$(srcdir)/'`mod_kafka.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-mod_kafka.Tpo $(DEPDIR)/almond-mod_kafka.Po
#	$(AM_V_CC)source='mod_kafka.c' object='almond-mod_kafka.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-mod_kafka.o `test -f 'mod_kafka.c' || echo '$(srcdir)/'`mod_kafka.c

almond-mod_kafka.obj: mod_kafka.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-mod_kafka.obj -MD -MP -MF $(DEPDIR)/almond-mod_kafka.Tpo -c -o almond-mod_kafka.obj `if test -f 'mod_kafka.c'; then $(CYGPATH_W) 'mod_kafka.c'; else $(CYGPATH_W) '$(srcdir)/mod_kafka.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-mod_kafka.Tpo $(DEPDIR)/almond-mod_kafka.Po
#	$(AM_V_CC)source='mod_kafka.c' object='almond-mod_kafka.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-mod_kafka.obj `if test -f 'mod_kafka.c'; then $(CYGPATH_W) 'mod_kafka.c'; else $(CYGPATH_W) '$(srcdir)/mod_kafka.c'; fi`

almond-mod_avro.o: mod_avro.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-mod_avro.o -MD -MP -MF $(DEPDIR)/almond-mod_avro.Tpo -c -o almond-mod_avro.o `test -f 'mod_avro.c' || echo '$(srcdir)/'`mod_avro.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-mod_avro.Tpo $(DEPDIR)/almond-mod_avro.Po
#	$(AM_V_CC)source='mod_avro.c' object='almond-mod_avro.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-mod_avro.o `test -f 'mod_avro.c' || echo '$(srcdir)/'`mod_avro.c

almond-mod_avro.obj: mod_avro.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -MT almond-mod_avro.obj -MD -MP -MF $(DEPDIR)/almond-mod_avro.Tpo -c -o almond-mod_avro.obj `if test -f 'mod_avro.c'; then $(CYGPATH_W) 'mod_avro.c'; else $(CYGPATH_W) '$(srcdir)/mod_avro.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/almond-mod_avro.Tpo $(DEPDIR)/almond-mod_avro.Po
#	$(AM_V_CC)source='mod_avro.c' object='almond-mod_avro.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(almond_CPPFLAGS) $(CPPFLAGS) $(almond_CFLAGS) $(CFLAGS) -c -o almond-mod_avro.obj `if test -f 'mod_avro.c'; then $(CYGPATH_W) 'mod_avro.c'; else $(CYGPATH_W) '$(srcdir)/mod_avro.c'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/almond-api.Po
	-rm -f ./$(DEPDIR)/almond-api_s.Po
	-rm -f ./$(DEPDIR)/almond-collect.Po
	-rm -f ./$(DEPDIR)/almond-config.Po
	-rm -f ./$(DEPDIR)/almond-jwt_validate.Po
	-rm -f ./$(DEPDIR)/almond-logger.Po
	-rm -f ./$(DEPDIR)/almond-main.Po
	-rm -f ./$(DEPDIR)/almond-main_s.Po
	-rm -f ./$(DEPDIR)/almond-mod_avro.Po
	-rm -f ./$(DEPDIR)/almond-mod_kafka.Po
	-rm -f ./$(DEPDIR)/almond-plugins.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/almond-api.Po
	-rm -f ./$(DEPDIR)/almond-api_s.Po
	-rm -f ./$(DEPDIR)/almond-collect.Po
	-rm -f ./$(DEPDIR)/almond-config.Po
	-rm -f ./$(DEPDIR)/almond-jwt_validate.Po
	-rm -f ./$(DEPDIR)/almond-logger.Po
	-rm -f ./$(DEPDIR)/almond-main.Po
	-rm -f ./$(DEPDIR)/almond-main_s.Po
	-rm -f ./$(DEPDIR)/almond-mod_avro.Po
	-rm -f ./$(DEPDIR)/almond-mod_kafka.Po
	-rm -f ./$(DEPDIR)/almond-plugins.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
