almond.api=true
almond.enableIamAud=false
almond.enforeIAMRoles=false
almond.iamAud=almond-api
#almond.iamIssuer=https://<host>/realms/<realm-name>
almond.iamIssuer=None
#almond.iamPublicKeyFile=/etc/almond/keycloak_pubkey.pem
almond.iamRolesAccepted=almond-exec
almond.port=9099
almond.pushUrl=host.docker.internal
almond.pushPort=8015
almond.pushInterval=120
almond.standalone=false
almond.useMetricsPush=false
almond.usePush=false
almond.useSSL=false
api.activeMods=modyaml.py
api.authProvider=local
api.authType=basic
api.bindPort=80
api.dataDir=/opt/almond/data
api.enableAliases=true
api.enableFile=true
api.enableGUI=true
api.enableLoginRedirect=false
api.enableMods=false
api.enableOath=false
api.enableOtelExporter=false
api.enableOtelFileWatcher=false
api.enablePeriodicOtelExport=true
api.enableProxyCleaner=false
api.enableScraper=true
api.enableSSL=false
api.isContainer=false
api.isMetricsProxy=false
api.isProxy=false
api.metricsDir=/opt/almond/data/metrics
api.otelExportInterval=60
api.otlpEndpoint=http://host.docker.internal:4318
api.persistant2fa=false
api.proxyCleanerSeconds=320
api.useSSL=false
api.showDashboard=on
api.sslCertificate=/opt/almond/www/api/ssl/cert.pem
api.sslKey=/opt/almond/www/api/ssl/key.pem
api.startPage=admin
api.stateType=systemctl
api.useSSL=false
api.userFile=/etc/almond/users.conf
api.wsgi=true
data.jsonFile=monitor_data.json
data.yamlFile=monitor.yaml
data.metricsFile=monitor.metrics
data.metricsOutputPrefix=almond
data.saveOnExit=false
gardener.CleanUpTime=86400
plugins.declaration=/etc/almond/plugins.conf
plugins.directory=/opt/almond/plugins
scheduler.clearDataCacheInterval=300
scheduler.confDir=/etc/almond
scheduler.confFile=/etc/almond/almond.conf
scheduler.dataCacheTimeFrame=false
scheduler.dataDir=/opt/almond/data
scheduler.enableClearDataCache=false
scheduler.enableGardener=true
scheduler.enableKafkaExport=false
scheduler.enableKafkaId=false
scheduler.enableKafkaSSL=false
scheduler.enableKafkaTag=false
scheduler.format=jsonprometheus
scheduler.gardenerRunInterval=43200
scheduler.gardenerScript=/opt/almond/gardener.py
scheduler.hostName=almond.demo.com
scheduler.initSleepMs=7000
scheduler.logDir=/var/log/almond
scheduler.logPluginOutput=true
scheduler.logToStdout=false
scheduler.quickStart=true
scheduler.runGardenerAtStart=false
scheduler.schemaName=almond-monitor-topic-value
scheduler.schemaRegistryUrl=http://localhost:8081
scheduler.sleepMs=5000
scheduler.storeDir=/opt/almond/data/metrics
scheduler.storeResults=true
scheduler.truncateLog=false
scheduler.truncateLogInterval=604800
scheduler.tuneTimer=false
scheduler.tunerCycle=15
scheduler.type=time
scheduler.useExternal=false
